Vagrant.configure("2") do |config|
  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "ubuntu/focal64"
    k8smaster.vm.box = "ubuntu/focal64"
    k8smaster.vm.box = "ubuntu/focal64"
    k8smaster.cpus = 1
  end
  config.vm.define "k8snode1" do |k8snode1|
    k8snode1.vm.box = "ubuntu/focal64"
    k8snode1.vm.box = "ubuntu/focal64"
    k8snode1.vm.box = "ubuntu/focal64"
    k8snode1.cpus = 1
  end
  config.vm.define "k8snode2" do |k8snode2|
    k8snode2.vm.box = "ubuntu/focal64"
    k8snode2.vm.box = "ubuntu/focal64"
    k8snode2.vm.box = "ubuntu/focal64"
    k8snode2.cpus = 1
  end
end
