Vagrant.configure("2") do |config|
  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "ubuntu/focal64"
    k8smaster.vm.hostname = "k8smaster"
    k8smaster.vm.network "private_network", ip: "192.168.100.11"
    k8smaster.vm.box_url = "ubuntu/focal64"
    k8smaster.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 1024
    end
  end
  config.vm.define "k8snode1" do |k8snode1|
    k8snode1.vm.box = "ubuntu/focal64"
    k8snode1.vm.hostname = "k8smaster"
    k8snode1.vm.network "private_network", ip: "192.168.100.21"
    k8snode1.vm.box_url = "ubuntu/focal64"
    k8snode1.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 512
    end
  end
  config.vm.define "k8snode2" do |k8snode2|
    k8snode2.vm.box = "ubuntu/focal64"
    k8snode2.vm.hostname = "k8smaster"
    k8snode2.vm.network "private_network", ip: "192.168.100.22"
    k8snode2.vm.box_url = "ubuntu/focal64"
    k8snode2.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 512
    end
  end
end
